### ISSUE TITLE
[Bug]: CheckboxPage crash application when open in new windows

### ISSUE THREAD

**Issue by Strypper** [Strypper/mauisland#123]
### Contact Details

ocgrb.strypperjason115@gmail.com

### What happened?

When you on Galley -> Built-in-> Check Box-> More detail to open the new page -> It can't do it and got out of the program
![2023-03-13 15-23-42](https://user-images.githubusercontent.com/82369529/224758356-c2c4ebf6-cd1e-41a9-914b-720a0bf96fa6.gif)

### Version

7.0

### What platforms are you seeing the problem on?

Windows

### Relevant log output

```shell
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in WinRT.Runtime.dll but was not handled in user code
The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))
```

### Code of Conduct

- [X] I agree to respect and follow this project's rules

**Comment by Strypper** [comment]
Transfered @E-vaTRON

**Comment by Strypper** [comment]
```
git fetch origin
git checkout 123-bug-checkboxpage-crash-application-when-open-in-new-windows
```

**Comment by E-vaTRON** [comment]
There was an unhandled exception
![image](https://user-images.githubusercontent.com/59007760/229776199-bb27ebb1-7396-481e-bb21-d0a44c27d446.png)
However, this bug only appears on the window version, not in the android one.

**Comment by E-vaTRON** [comment]
Problem solved the Default FontSize can not be rendered in the new window
Solution: Remove FontSize="Default" property from <Label>
