### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by Strypper** [Strypper/mauisland#150]
All syncfusion cards have the wrong github link
SfBadgeView miss sf logo - detail page
SfCombobox miss commands logo (2) - detail page
SfBusyIndicator miss commands logo (2) - detail page
SfCartersianChart miss commands logo (2) - detail page
SfListView miss commands logo (2) - detail page
SfMapsView miss sf logo - detail page
SfRangeSelector miss commands logo (2) - detail page

Frame need review
ImageButton need code attach
RadioButton need review
Refresh view need update
Searchbar need change icon color

**Comment by E-vaTRON** [comment]
Remain
ImageButton need update
RadioButton need review
RefreshView need update

**Comment by E-vaTRON** [comment]
Remain
RefreshView need update
