### ISSUE TITLE
[Bug]: Collection View span on Windows doesn't change dynamically

### ISSUE THREAD

**Issue by truonghocyeuquy** [Strypper/mauisland#43]
### What happened?

Collection view span should change its value dynamically like it normally does on Android. 

Check this out on:

https://1drv.ms/v/s!Atp5h2QiqzrFidI4ob-_Odk7H_KEfA?e=j1cQax

Expected: 

https://1drv.ms/v/s!Atp5h2QiqzrFidI3Kjial64ufZ9FmQ?e=YovIy3

### Version

.NET 7

### What platform are you seeing the problem on?

_Windows_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Strypper** [comment]
This is so bad the MAUI team should give us the GridView control, this unacceptable for building desktop application

**Comment by Strypper** [comment]
Currently still no fix for this, we will stick with the HorizontalWrapLayout for temporary solution for displaying all control cards
