### ISSUE TITLE
[Restriction]: Windows require Page datatype rather than URL

### ISSUE THREAD

**Issue by truonghocyeuquy** [Strypper/mauisland#44]
### Contact Details

maiminhhoang113@gmail.com

### What happened?

Windows require Page datatype to lead to a different page and it doesn't allow page navigation through URL.

Temporary Solution:
Create a third page called: "BridgeWindowChat.xaml" to render the URL and then use it as a Page datatype to Navigate.

### Version

6.0 (Default)

### Code of Conduct

- [X] I agree to respect and follow this project's rules

**Comment by tuyen-vuduc** [comment]
- Check out latest code
- Possibly merge my open PR first

**Comment by Strypper** [comment]
> * Check out latest code
> * Possibly merge my open PR first

Yes the new PR fix this issue nicely, thanks you !!!!
