### ISSUE TITLE
SFComboBox

### ISSUE THREAD

**Issue by Strypper** [Strypper/mauisland#82]
### Description

![image](https://user-images.githubusercontent.com/32596308/217636501-e340147d-719b-4ea7-b38e-300272d620a5.png)

[Control detail](https://help.syncfusion.com/maui/combobox/overview)

The [.NET MAUI ComboBox](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.Inputs.SfComboBox.html) control is a selection component that allows users to type a value or choose an option from a list of predefined options. It has many features, such as data binding, editing, searching, clear button and dropdown button customization, and more.

### Public API Changes

```xml
xmlns:editors="clr-namespace:Syncfusion.Maui.Inputs;assembly=Syncfusion.Maui.Inputs"
```

```xml
<ContentPage.Content>    
    <editors:SfComboBox x:Name="comboBox" />
</ContentPage.Content>
```

### Intended Use-Case

Data binding – Support binding various types of data sources.
Editable mode – Editable and non-editable text boxes to select items from the given data source.
Filtering – The ComboBox filters items based on the entered text and auto-fills with the first suggestion.
Searching – Highlights the matching item in the drop-down list based on the provided input.
Placeholder – Display placeholder text inside the control until the user enters text.

**Comment by Strypper** [comment]
@ViperTricks Start this
```
git fetch origin
git checkout 82-sfcombobox
```

**Comment by ViperTricks** [comment]
Ok, thank you sir
