### ISSUE TITLE
[Feature]: SFMap

### ISSUE THREAD

**Issue by Strypper** [Strypper/mauisland#92]
### Description

The .NET MAUI Maps control is a powerful data visualization component that displays statistical information for a geographical area. It has highly interactive and customizable features such as selection, tooltip, legends, markers, bubbles, and color mapping. Using the Maps control, you can generate maps for population density, sales, political boundaries, weather, elections, and routes.

### Public API Changes

```xml
<map:SfMaps>
  
</map:SfMaps>
```

```cs
SfMaps map = new SfMaps();
	
this.Content = map;
```

### Intended Use-Case

1. [Shape layer](https://help.syncfusion.com/maui/maps/getting-started#add-shape-layer-maps-elements) - Visualize the map area from GeoJSON or shapefile input data.
2. [Data labels](https://help.syncfusion.com/maui/maps/data-labels) - Provide identification for shapes by displaying their names. If the labels exceed the shape bounds, they are trimmed or hidden.
3. [Markers](https://help.syncfusion.com/maui/maps/markers) - Denote a location with built-in symbols or display custom content at a specific latitude and longitude on a map.
4. [Bubbles](https://help.syncfusion.com/maui/maps/bubble) - Add information to shapes such as population density or number of users. Bubbles can be rendered in different colors and sizes based on the data values of their assigned shapes.
5. [Shape selection](https://help.syncfusion.com/maui/maps/selection) - Choose a shape to highlight a region on a map. You can use the event for performing action during the shape selection.
6. [Legend](https://help.syncfusion.com/maui/maps/legend) - Use legends to provide clear information on the data plotted in a map.
7. [Colors](https://help.syncfusion.com/maui/maps/shape) - Categorize the shapes on a map by assigning their colors based on their underlying values. It is possible to set the shape color for a specific value or for a range of values.
8. [Tooltip](https://help.syncfusion.com/maui/maps/tooltip) - Display additional information about shapes, markers, and bubbles using a customizable tooltip on a map.

**Comment by Strypper** [comment]
```
git fetch origin
git checkout 92-sfmap
```

**Comment by kendy78** [comment]
`dotnet cake --group Syncfusion --name SfMap --cardDetail "The .NET MAUI Maps control is a powerful data visualization component that displays statistical information for a geographical area. It has highly interactive and customizable features such as selection, tooltip, legends, markers, bubbles, and color mapping. Using the Maps control, you can generate maps for population density, sales, political boundaries, weather, elections, and routes." --originalDocumentUrl "https://help.syncfusion.com/maui/maps/overview"`
